### ISSUE TITLE
How do I save the session key

### ISSUE THREAD

**Issue by yunzhiyan** [dantmnf/tdlib-netcore#6]
I want to save the login session. What should I do？

**Comment by dantmnf** [comment]
The session key is managed by tdlib and will be saved to the database directory specified in TdlibParameters and will be picked up (if exists) on setTdlibParameters call.

**Comment by yunzhiyan** [comment]
I want to save the session key for multiple accounts, but I don't know how to get it. How can I get it？

**Comment by dantmnf** [comment]
AFAIK there is no easy way to do this. Even though you obtained the key somewhere you have no public API to use it with tdlib.

You can use different database directories for multiple accounts but it may produce some duplicate downloads.

**Comment by yunzhiyan** [comment]
Thanks.

**Comment by yunzhiyan** [comment]
那个，大佬是中国的吗？
